Update Dutch translations (thanks David Ferretti)
zbrateam/Zebra pull request #2016
Opened 2022-12-19 17:07 UTC by iAdam1n

2022-12-20 06:12 UTC, kirb requested changes

2022-12-20 06:12 UTC, kirb commented on Zebra/Supporting Files/Resources/nl.lproj/Localizable.strings
> +"Transfer Sources" = "importeer bronnen";
Is the capitalisation on this and a few other lines below correct?

2022-12-20 06:41 UTC, iAdam1n commented on Zebra/Supporting Files/Resources/nl.lproj/Localizable.strings
> +"Transfer Sources" = "importeer bronnen";
Eh he didn’t seem to do the right case and I forgot to check. Fixed now.

2023-04-24 07:10 UTC, kirb commented
Cherry-picked in with 3c7954eb

2023-04-24 07:10 UTC, closed without merging